/***************************************************************************
  * Title:          
  * Author:         Sangtae Kim
  * Last modified:  
  *
  * Copyright (c) 2008-2009 The Regents of the University of California
  * All Rights Reserved
  * See file LICENSE for details.
  ***************************************************************************/
package uninovo.util;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;


/**
 * This class represents an enzyme.
 * 
 * @author sangtaekim
 */
public class Enzyme {
	
	/** The Constant ArgC. */
	public static final Enzyme ArgC;
	
	/** The Constant AspN. */
	public static final Enzyme AspN;
	
	/** The Constant CHYMOTRYPSIN. */
	public static final Enzyme CHYMOTRYPSIN;
	/** The Constant GluC. */
	public static final Enzyme GluC; 
	
	/** The Constant LysC. */
	public static final Enzyme LysC;
	/** The Constant LysN. */
	public static final Enzyme LysN;
	
	private static HashMap<String,Enzyme> registeredEnzyme;
	
	/** The Constant TRYPSIN. */
	public static final Enzyme TRYPSIN;	
	static {
		TRYPSIN = new Enzyme("Tryp", "KR", false);
		TRYPSIN.setNeighboringAAEfficiency(0.9148273f);
		TRYPSIN.setPeptideCleavageEffiency(0.98173124f);
		
		CHYMOTRYPSIN = new Enzyme("CHYMOTRYPSIN", "FYWL", false);
		
		LysC = new Enzyme("LysC", "K", false);
		LysC.setNeighboringAAEfficiency(0.79f);
		LysC.setPeptideCleavageEffiency(0.89f);
		
		LysN = new Enzyme("LysN", "K", true);
		GluC = new Enzyme("GluC","E",false);
		ArgC = new Enzyme("ArgC","R",false);
		AspN = new Enzyme("AspN","D",true);
		registeredEnzyme = new HashMap<String,Enzyme>();

		register("Tryp", TRYPSIN);
		register("CHYMOTRYPSIN", CHYMOTRYPSIN);
		register("LysC", LysC);
		register("LysN", LysN);
		register("GluC", GluC);
		register("ArgC", ArgC);
		register("AspN", AspN);
	}
	public static Enzyme getEnzymeByName(String name)
	{
		return registeredEnzyme.get(name);
	}
	
	public static void register(String name, Enzyme enzyme)
	{
		registeredEnzyme.put(name, enzyme);
	}
	private CompositionAASet compositionAASet;
	/** True if the enzyme cleaves n-terminus, false otherwise. */
	private boolean isNTerm;
	
	private boolean[] isResidueCleavable;
	
	/** Name of the enzyme. */
	private String name;

	private int neighboringAACleavageCredit = 0;

	// the probability that a neighboring amino acid follows the enzyme rule
	// E.g. for trypsin, probability that the preceding amino acid is K or R
	private float neighboringAACleavageEfficiency;
	
	private int neighboringAACleavagePenalty = 0;
	private NominalMassAASet nominalMassAASet;
	
	private int peptideCleavageCredit = 0;
	
	// the probability that a peptide generated by this enzyme follows the cleavage rule
	// E.g. for trypsin, probability that a peptide ends with K or R
	private float peptideCleavageEfficiency;
	
	private int peptideCleavagePenalty = 0;
	private float probCleavageSites;
	
	/** Amino acid residues cleaved by the enzyme. */
	private ArrayList<AminoAcid> residues;
	
	/**
	 * Instantiates a new enzyme.
	 * 
	 * @param name the name
	 * @param residues the residues cleaved by the enzyme (HashSet)
	 * @param isNTerm N term or C term (true if it cleaves N-term)
	 */
	private Enzyme(String name, ArrayList<AminoAcid> residues, boolean isNTerm) 
	{
		this.name = name;
		this.residues = residues;
		this.isNTerm = isNTerm;
		initResidues();
	}
	
	/**
	 * Instantiates a new enzyme.
	 * 
	 * @param name the name
	 * @param residues the residues cleaved by the enzyme (String)
	 * @param isNTerm N term or C term (true if it cleaves N-term)
	 */
	private Enzyme(String name, String residues, boolean isNTerm) 
	{
		this.name = name;
		this.residues = new ArrayList<AminoAcid>();
		for(int i=0; i<residues.length(); i++)
			this.residues.add(AminoAcid.getStandardAminoAcid(residues.charAt(i)));
		this.isNTerm = isNTerm;
		initResidues();
	}
	
	public CompositionAASet getCompefficiencyositionAASet()	{ return compositionAASet; }

	public IntMassAASet getIntMassAASet(IntMassFactory factory)
	{
		return new IntMassAASet(factory, residues);
	}
	
	
	/**
	 * Returns the name of the enzyme.
	 * 
	 * @return the name of the enzyme.
	 */
	public String getName()		{ return name; }
	
	public int getNeighboringAACleavageCredit() { return neighboringAACleavageCredit; }
	
	/**
	 * Gets the neighboring amino acid efficiency
	 * @return neighboring amino acid efficiency
	 */
	public float getNeighboringAACleavageEffiency() { return neighboringAACleavageEfficiency; }
	
	public int getNeighboringAACleavagePenalty() { return neighboringAACleavagePenalty; }
	
	public NominalMassAASet getNominalMassAASet()	{ return nominalMassAASet; }
	
	/**
	 * Returns the number of cleavaged termini
	 * @param annotation annotation (e.g. K.DLFGEK.I)
	 * @return the number of cleavaged termini
	 */
	public int getNumCleavedTermini(String annotation, AminoAcidSet aaSet)
	{
		int nCT = 0;
		String pepStr = annotation.substring(annotation.indexOf('.')+1, annotation.lastIndexOf('.'));
		Peptide peptide = aaSet.getPeptide(pepStr);
		if(this.isCleaved(peptide))
			nCT++;
		
		AminoAcid precedingAA = aaSet.getAminoAcid(annotation.charAt(0));
		AminoAcid nextAA = aaSet.getAminoAcid(annotation.charAt(annotation.length()-1));
		if(this.isNTerm)
		{
			if(nextAA == null || this.isCleavable(nextAA))
				nCT++;
		}
		else
		{
			if(precedingAA == null || this.isCleavable(precedingAA))
				nCT++;
		}
		
		return nCT;
	}
	
	public int getPeptideCleavageCredit() { return peptideCleavageCredit; }
	/**
	 * Gets the peptide efficiency.
	 * @return peptide efficiency
	 */
	public float getPeptideCleavageEfficiency()	{ return peptideCleavageEfficiency; }
	public int getPeptideCleavagePenalty() { return peptideCleavagePenalty; }
	
	/**
	 * Gets the probability sum of cleavage sites
	 * @param aaSet amino acid set.
	 * @return the probability sum of cleavage sites.
	 */
	public float getProbCleavageSites()
	{
		return probCleavageSites;
	}
	
	/**
	 * Gets the residues.
	 * 
	 * @return the residues
	 */
	public ArrayList<AminoAcid> getResidues()	{ return residues; }
	
	@Override
	public int hashCode() {
		return name.hashCode();
	}
	
	private void initResidues()
	{
		Collections.sort(residues);
		nominalMassAASet = new NominalMassAASet(residues);
		compositionAASet = new CompositionAASet(residues);
		probCleavageSites = 0;
		for(AminoAcid aa : residues)
			probCleavageSites += aa.getProbability();
		isResidueCleavable = new boolean[128];
		for(AminoAcid aa : residues)
			isResidueCleavable[aa.getResidue()] = true;
	}
	
	/**
	 * Checks if the amino acid is cleavable.
	 * 
	 * @param aa the amino acid
	 * 
	 * @return true, if aa is cleavable
	 */
	public boolean isCleavable(AminoAcid aa)
	{
		return residues.contains(aa);
	}
	
	/**
	 * Checks if the amino acid is cleavable.
	 * 
	 * @param residue amino acid residue
	 * 
	 * @return true, if residue is cleavable
	 */
	public boolean isCleavable(char residue)
	{
		return isResidueCleavable[residue];
	}
	
	/**
	 * Checks if the peptide is cleaved by the enzyme.
	 * @param p peptide
	 * @return true if p is cleaved, false otherwise.
	 */
	public boolean isCleaved(Peptide p)
	{
		AminoAcid aa;
		if(isNTerm)
			aa = p.get(0);
		else
			aa = p.get(p.size()-1);
		return isCleavable(aa);
	}
	
	/**
	 * Checks if this enzyme cleaves C term.
	 * 
	 * @return true, if it cleaves C term.
	 */
	public boolean isCTerm()	{ return !isNTerm; }
	
	/**
	 * Checks if this enzyme cleaves N term.
	 * 
	 * @return true, if it cleaves N term.
	 */
	public boolean isNTerm()	{ return isNTerm; }
	
	/**
	 * Sets the neighboring amino acid efficiency as the probability that a neighboring amino acid follows the enzyme rule
	 * @param neighboringAACleavageEfficiency neighboring amino acid effieicncy
	 * @return this object
	 */
	public void setNeighboringAAEfficiency(float neighboringAACleavageEfficiency)
	{
		this.neighboringAACleavageEfficiency = neighboringAACleavageEfficiency;
		this.neighboringAACleavageCredit = (int)Math.round(Math.log(neighboringAACleavageEfficiency/this.probCleavageSites));
		this.neighboringAACleavagePenalty = (int)Math.round(Math.log((1-neighboringAACleavageEfficiency)/(1-this.probCleavageSites)));
	}
	
	/**
	 * Sets the peptide cleavage efficiency as the probability that a peptide generated by this enzyme follows the cleavage rule
	 * @param peptideCleavageEfficiency peptide cleagave efficiency
	 * @return this object
	 */
	public void setPeptideCleavageEffiency(float peptideCleavageEfficiency)
	{
		this.peptideCleavageEfficiency = peptideCleavageEfficiency;
		this.peptideCleavageCredit = (int)Math.round(Math.log(peptideCleavageEfficiency/this.probCleavageSites));
		this.peptideCleavagePenalty = (int)Math.round(Math.log((1-peptideCleavageEfficiency)/(1-this.probCleavageSites)));
	}
	
	/** 
	 * Sets probCleavageSites. Cleavage penalty/credit must be re-computed.
	 * @param probCleavageSites
	 */
	public void setProbCleavageSites(float probCleavageSites)
	{
		this.probCleavageSites = probCleavageSites;
		this.peptideCleavageCredit = (int)Math.round(Math.log(peptideCleavageEfficiency/this.probCleavageSites));
		this.peptideCleavagePenalty = (int)Math.round(Math.log((1-peptideCleavageEfficiency)/(1-this.probCleavageSites)));
		this.neighboringAACleavageCredit = (int)Math.round(Math.log(neighboringAACleavageEfficiency/this.probCleavageSites));
		this.neighboringAACleavagePenalty = (int)Math.round(Math.log((1-neighboringAACleavageEfficiency)/(1-this.probCleavageSites)));
	}
}
